name: Build Services
on:
  workflow_dispatch:
    inputs:
      services:
        description: 'List of services to build'
        required: true

jobs:
  build:
    strategy:
      matrix:
        service: ${{ fromYaml(file.path('./.scripts/services_matrix_config.yaml')) }}
        include:
          - service: ${{fromJson(inputs.services)}}
            build: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Service
        if: matrix.build == 'true'
        run: |
          echo "Building ${{ matrix.service.ECS_SERVICE }}"
          echo "Using project name: ${{ matrix.service.PROJECT_NAME }}"
          echo "Using service path: ${{ matrix.service.SERVICE_PATH }}"
