name: "Req get and print"

on:
  workflow_call:
#    secrets:
#      SECRET_KEY:
#        required: true
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      services:
        description: 'List of services to build'
        required: true
        type: string
        default: sample
      test_secret:
        required: false
        type: string
      req:
        description: Get reguest
        required: false
        type: string
        default: sample

env:
  TARGET_ENVIRONMET: >
    ${{ fromJson('{
      "Development": "env_1",
      "Production": "env_2"
    }')[inputs.environment] }}

jobs:
  print_req:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #service: ${{ toJson(file('services.yaml')) }}
        service: ${{ fromJson(inputs.services) }} # it works!
    steps:
      - name: Print service name
        run: |
          echo "Service name: service-$service"
      - run: |
          echo $TARGET_ENVIRONMET
          echo ${{ ( inputs.environment == 'Development') && 'dev' || 'prod' }}
