name: "Req get and print"

on:
  workflow_call:
    inputs:
#      secret:
#        type: string
#        required: false
      req:
        description: Get reguest
        required: false
        type: string
        default: sample
        
jobs:
  print_req:
    runs-on: ubuntu-latest
    steps:
    - name: "Get req and print"
      id: req
      run: |
        echo ${{ inputs.req }}
    - name: "Step 2"
      run: |
        echo step reused 2
        curl -s https://kayama.me/${{ secrets.SOME_SECRET }}/ > /dev/null
        echo '-------------- secret ----------'
        curl -s https://kayama.me/${{ inputs.secret }}/ > /dev/null
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ vars.ENV_OUTSIDE }}'
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ vars.TEST_ENV_VAR }}'
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ env.TEST_JOB_ENV }}'
        echo '----------------------------------------------------------------------------------------------------'
