name: "Req get and print"

on:
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      test_secret:
        required: false
        type: string
      req:
        description: Get reguest
        required: false
        type: string
        default: sample
        
jobs:
  print_req:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: "Get req and print"
      id: req
      run: |
        echo ${{ inputs.req }}
        echo ${{ inputs.test_secret }}
    - name: "Step 2"
      run: |
        echo step reused 2
        curl -s https://kayama.me/${{ secrets.SECRET_KEY }}/ > /dev/null
        echo ${{ secrets.SECRET_KEY }}/ > secret.file
        cat secret.file
        echo '-------------- secret ----------'
        curl -s https://kayama.me/${{ inputs.secret }}/ > /dev/null
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ vars.ENV_OUTSIDE }}'
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ vars.TEST_ENV_VAR }}'
        echo '----------------------------------------------------------------------------------------------------'
        echo '${{ env.TEST_JOB_ENV }}'
        echo '----------------------------------------------------------------------------------------------------'
